version: '2.3'
services:
  object-detection-ssd-gpu:
    runtime: nvidia
    image: registry.insight-centre.org/sit/mps/felipe-phd/object-detection-service:${IMAGE_TAG}-gpu
    command: python /service/object_detection_service/run.py

    depends_on:
     - redis
     - service-registry
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${OBJECT_DETECTION_SSD_GPU_STREAM_KEY}
      - SERVICE_CMD_KEY=${OBJECT_DETECTION_SSD_GPU_CMD_KEY}
      - SERVICE_REGISTRY_CMD_KEY=${SERVICE_REGISTRY_CMD_KEY}
      - SERVICE_DETAILS_SERVICE_TYPE=ObjectDetection
      - SERVICE_DETAILS_CONTENT_TYPES=node_attribute:bounding_box,node_attribute:label,node_attribute:confidence,node:person,node:car
      - SERVICE_DETAILS_STREAM_KEY=${OBJECT_DETECTION_SSD_GPU_STREAM_KEY}
      - SERVICE_DETAILS_QUEUE_LIMIT=100
      - SERVICE_DETAILS_THROUGHPUT=10.4
      - SERVICE_DETAILS_ACCURACY=0.9
      - SERVICE_DETAILS_ENERGY_CONSUMPTION=108
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - PYTHONUNBUFFERED=0
      - CUDA_VISIBLE_DEVICES=0
      - GPU_SUPPORT_FLAG=1
      - DNN_TF_GPU_FRACTION=1.0
      - MODEL_NAME=ssd_mobilenet_v1_coco_2017_11_17
      - INPUT_WIDTH=300
      - INPUT_HEIGHT=300
      - DETECTION_THRESHOLD=0.5
      - ALLOW_MEMORY_GROWTH=True
      - LOGGING_LEVEL=DEBUG

  object-detection-ssd:
    image: registry.insight-centre.org/sit/mps/felipe-phd/object-detection-service:${IMAGE_TAG}
    command: python /service/object_detection_service/run.py

    depends_on:
     - redis
     - service-registry
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${OBJECT_DETECTION_SSD_STREAM_KEY}
      - SERVICE_CMD_KEY=${OBJECT_DETECTION_SSD_CMD_KEY}
      - SERVICE_REGISTRY_CMD_KEY=${SERVICE_REGISTRY_CMD_KEY}
      - SERVICE_DETAILS_SERVICE_TYPE=ObjectDetection
      - SERVICE_DETAILS_CONTENT_TYPES=node_attribute:bounding_box,node_attribute:label,node_attribute:confidence,node:person,node:car
      - SERVICE_DETAILS_STREAM_KEY=${OBJECT_DETECTION_SSD_STREAM_KEY}
      - SERVICE_DETAILS_QUEUE_LIMIT=100
      - SERVICE_DETAILS_THROUGHPUT=10.4
      - SERVICE_DETAILS_ACCURACY=0.9
      - SERVICE_DETAILS_ENERGY_CONSUMPTION=108
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - PYTHONUNBUFFERED=0
      - CUDA_VISIBLE_DEVICES=-1
      - GPU_SUPPORT_FLAG=0
      - MODEL_NAME=ssd_mobilenet_v1_coco_2017_11_17
      - INPUT_WIDTH=300
      - INPUT_HEIGHT=300
      - DETECTION_THRESHOLD=0.5
      - ALLOW_MEMORY_GROWTH=True
      - LOGGING_LEVEL=DEBUG