version: '2.3'
services:
  redis:
    image: redislabs/redisgraph:2.2.5
    ports:
      - "6379:6379"
    mem_limit: 4gb
    environment:
      - PYTHONUNBUFFERED=0

  jaeger:
    image: jaegertracing/all-in-one:1.14
    command: --log-level=debug
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  adaptation-knowledge:
    image: registry.insight-centre.org/sit/mps/adaptation-knowledge:${IMAGE_TAG}
    command: python /service/adaptation_knowledge/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_KNOWLEDGE_STREAM_KEY}
      - SERVICE_CMD_KEY=${ADAPTATION_KNOWLEDGE_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  adaptation-monitor:
    image: registry.insight-centre.org/sit/mps/adaptation-monitor:${IMAGE_TAG}
    command: python /service/adaptation_monitor/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_MONITOR_STREAM_KEY}
      - SERVICE_CMD_KEY=${ADAPTATION_MONITOR_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  adaptation-analyser:
    image: registry.insight-centre.org/sit/mps/adaptation-analyser:${IMAGE_TAG}
    command: python /service/adaptation_analyser/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_ANALYSER_STREAM_KEY}
      - SERVICE_CMD_KEY=${ADAPTATION_ANALYSER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  adaptation-planner:
    image: registry.insight-centre.org/sit/mps/adaptation-planner:${IMAGE_TAG}
    command: python /service/adaptation_planner/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_PLANNER_STREAM_KEY}
      - SERVICE_CMD_KEY=${ADAPTATION_PLANNER_CMD_KEY}
      - MOCKED_OD_STREAM_KEY=${ADAPTATION_PLANNER_MOCKED_OD_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG

  query-manager:
    image: registry.insight-centre.org/sit/mps/query-manager:${IMAGE_TAG}
    command: python /service/query_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${QUERY_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${QUERY_MANAGER_CMD_KEY}
      - NAMESPACE_MAPPER_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - MATCHER_CMD_KEY=${MATCHER_CMD_KEY}
      - QUERY_PLANNER_CMD_KEY=${QUERY_PLANNER_CMD_KEY}
      - FORWARDER_CMD_KEY=${FORWARDER_CMD_KEY}
      - WINDOW_MANAGER_CMD_KEY=${WINDOW_MANAGER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  query-planner:
    image: registry.insight-centre.org/sit/mps/query-planner:${IMAGE_TAG}
    command: python /service/query_planner/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${QUERY_PLANNER_STREAM_KEY}
      - SERVICE_CMD_KEY=${QUERY_PLANNER_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - FINAL_DESTINATION_KEY=${FINAL_DESTINATION_KEY}
      - LOGGING_LEVEL=DEBUG

  preprocessor:
    image: registry.insight-centre.org/sit/mps/preprocessing-service:${IMAGE_TAG}
    command: python /service/preprocessing/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${PREPROCESSOR_STREAM_KEY}
      - SERVICE_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - FFMPEG_BIN=/service/ffmpeg_bin/ffmpeg-linux64-v3.3.1
      - REDIS_EXPIRATION_TIME=100
      - LOGGING_LEVEL=DEBUG

  namespace-mapper:
    image: registry.insight-centre.org/sit/mps/namespace-mapper:${IMAGE_TAG}
    command: python /service/namespace_mapper/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${NAMESPACE_MAPPER_STREAM_KEY}
      - SERVICE_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - PREPROCESSOR_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  scheduler:
    image: registry.insight-centre.org/sit/mps/scheduler:${IMAGE_TAG}
    command: python /service/scheduler/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${SCHEDULER_STREAM_KEY}
      - SERVICE_CMD_KEY=${SCHEDULER_CMD_KEY}
      - EVENT_DISPATCHER_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG

  event-dispatcher:
    image: registry.insight-centre.org/sit/mps/event-dispatcher:${IMAGE_TAG}
    command: python /service/event_dispatcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  window-manager:
    image: registry.insight-centre.org/sit/mps/window-manager:${IMAGE_TAG}
    command: python /service/window_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${WINDOW_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${WINDOW_MANAGER_CMD_KEY}
      - STATE_MANAGER_CMD_KEY=${STATE_MANAGER_CMD_KEY}
      - STATE_MANAGER_STREAM_KEY=${STATE_MANAGER_STREAM_KEY}
      - MATCHER_STREAM_KEY=${MATCHER_STREAM_KEY}
      - MATCHER_CMD_KEY=${MATCHER_CMD_KEY}
      - EDGE_OPERATORS=${EDGE_OPERATORS}
      - LOGGING_LEVEL=DEBUG

  matcher:
    image: registry.insight-centre.org/sit/mps/matcher:${IMAGE_TAG}
    command: python /service/matcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${MATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${MATCHER_CMD_KEY}
      - FORWARDER_STREAM_KEY=${FORWARDER_STREAM_KEY}
      - FORWARDER_CMD_KEY=${FORWARDER_CMD_KEY}
      - IMAGE_ANNOTATOR_SERVICE_STREAM_KEY=${IMAGE_ANNOTATOR_SERVICE_STREAM_KEY}
      - ENABLED_ANNOTATION_ENCODING=${ENABLED_ANNOTATION_ENCODING}
      - LOGGING_LEVEL=DEBUG

  image-annotator-service:
    image: registry.insight-centre.org/sit/mps/image-annotator-service:${IMAGE_TAG}
    command: python /service/image_annotator/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${IMAGE_ANNOTATOR_SERVICE_STREAM_KEY}
      - SERVICE_CMD_KEY=${IMAGE_ANNOTATOR_SERVICE_CMD_KEY}
      - FORWARDER_STREAM_KEY=${FORWARDER_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG

  forwarder:
    image: registry.insight-centre.org/sit/mps/forwarder:${IMAGE_TAG}
    command: python /service/forwarder/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${FORWARDER_STREAM_KEY}
      - SERVICE_CMD_KEY=${FORWARDER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  object-detection-ssd:
    image: registry.insight-centre.org/sit/mps/object-detection-service:${IMAGE_TAG}
    command: python /service/object_detection_service/run.py

    depends_on:
     - redis
    environment:
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${OBJECT_DETECTION_SSD_STREAM_KEY}
      - SERVICE_CMD_KEY=${OBJECT_DETECTION_SSD_CMD_KEY}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - PYTHONUNBUFFERED=0
      - CUDA_VISIBLE_DEVICES=-1
      - GPU_SUPPORT_FLAG=0
      - MODEL_NAME=ssd_mobilenet_v1_coco_2017_11_17
      - INPUT_WIDTH=300
      - INPUT_HEIGHT=300
      - DETECTION_THRESHOLD=0.5
      - ALLOW_MEMORY_GROWTH=True
      - LOGGING_LEVEL=DEBUG

  color-detection:
    image: registry.insight-centre.org/sit/mps/color-detection-service:${IMAGE_TAG}
    command: python /service/color_detection_service/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${COLOR_DETECTION_STREAM_KEY}
      - SERVICE_CMD_KEY=${COLOR_DETECTION_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  client-manager:
    image: registry.insight-centre.org/sit/mps/client-manager:${IMAGE_TAG}
    command: python /service/client_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${CLIENT_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${CLIENT_MANAGER_CMD_KEY}
      - QUERY_MANAGER_CMD_KEY=${QUERY_MANAGER_CMD_KEY}
      - NAMESPACE_MAPPER_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
