version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

  media-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - "./media_server/media_files:/var/media_files"
      - "./media_server/nginx.conf:/etc/nginx/nginx.conf"

  preprocessor:
    # runtime: nvidia
    image: registry.insight-centre.org/sit/mps/preprocessing-service:latest
    command: python /service/preprocessing/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${PREPROCESSOR_STREAM_KEY}
      - SERVICE_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - FFMPEG_BIN=/service/ffmpeg_bin/ffmpeg-linux64-v3.3.1
      - LOGGING_LEVEL=DEBUG
    cpus: 2

  namespace-mapper:
    image: registry.insight-centre.org/sit/mps/namespace-mapper:latest
    command: python /service/namespace_mapper/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${NAMESPACE_MAPPER_STREAM_KEY}
      - SERVICE_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - PREPROCESSOR_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  event-dispatcher:
    image: registry.insight-centre.org/sit/mps/event-dispatcher:latest
    command: python /service/event_dispatcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  window-manager:
    image: registry.insight-centre.org/sit/mps/window-manager:latest
    command: python /service/window_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${WINDOW_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${WINDOW_MANAGER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25
