version: '2.3'
services:
  media-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - "./media_server/media_files:/var/media_files"
      - "./media_server/nginx.conf:/etc/nginx/nginx.conf"
