version: '2.3'
services:
  redis:
    image: redislabs/redisgraph:2.2.5
    ports:
      - "6379:6379"
    mem_limit: 4gb
    environment:
      - PYTHONUNBUFFERED=0

  jaeger:
    image: jaegertracing/all-in-one:1.14
    command: --log-level=debug
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411

  client-manager:
    image: registry.insight-centre.org/sit/mps/felipe-phd/client-manager:${IMAGE_TAG}
    command: python /service/client_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${CLIENT_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${CLIENT_MANAGER_CMD_KEY}
      - PREPROCESSOR_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - ADAPTATION_MONITOR_CMD_KEY=${ADAPTATION_MONITOR_CMD_KEY}
      - MOCKED_SERVICE_REGISTRY=${MOCKED_SERVICE_REGISTRY}
      - LOGGING_LEVEL=DEBUG

  adaptation-knowledge:
    image: registry.insight-centre.org/sit/mps/felipe-phd/adaptation-knowledge:${IMAGE_TAG}
    command: python /service/adaptation_knowledge/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_KNOWLEDGE_STREAM_KEY}
      - SERVICE_CMD_KEY=${ADAPTATION_KNOWLEDGE_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  adaptation-monitor:
    image: registry.insight-centre.org/sit/mps/felipe-phd/adaptation-monitor:${IMAGE_TAG}
    command: python /service/adaptation_monitor/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_MONITOR_STREAM_KEY}
      - MOCKED_WORKERS_ENERGY_USAGE_DICT=${MOCKED_WORKERS_ENERGY_USAGE_DICT}
      - SERVICE_CMD_KEY=${ADAPTATION_MONITOR_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  adaptation-analyser:
    image: registry.insight-centre.org/sit/mps/felipe-phd/adaptation-analyser:${IMAGE_TAG}
    command: python /service/adaptation_analyser/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_ANALYSER_STREAM_KEY}
      - SERVICE_CMD_KEY=${ADAPTATION_ANALYSER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  adaptation-planner:
    image: registry.insight-centre.org/sit/mps/felipe-phd/adaptation-planner:${IMAGE_TAG}
    command: python /service/adaptation_planner/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${ADAPTATION_PLANNER_STREAM_KEY}
      - SERVICE_CMD_KEY=${ADAPTATION_PLANNER_CMD_KEY}
      - MOCKED_OD_STREAM_KEY=${ADAPTATION_PLANNER_MOCKED_OD_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG

  preprocessor:
    image: registry.insight-centre.org/sit/mps/felipe-phd/preprocessing-service:${IMAGE_TAG}
    command: python /service/preprocessing/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${PREPROCESSOR_STREAM_KEY}
      - SERVICE_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - FFMPEG_BIN=/service/ffmpeg_bin/ffmpeg-linux64-v3.3.1
      - REDIS_EXPIRATION_TIME=100
      - LOGGING_LEVEL=DEBUG

  event-dispatcher:
    image: registry.insight-centre.org/sit/mps/felipe-phd/event-dispatcher:${IMAGE_TAG}
    command: python /service/event_dispatcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG

  scheduler:
    image: registry.insight-centre.org/sit/mps/felipe-phd/scheduler:${IMAGE_TAG}
    command: python /service/scheduler/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${SCHEDULER_STREAM_KEY}
      - SERVICE_CMD_KEY=${SCHEDULER_CMD_KEY}
      - EVENT_DISPATCHER_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG


  # forwarder:
  #   image: registry.insight-centre.org/sit/mps/felipe-phd/forwarder:${IMAGE_TAG}
  #   command: python /service/forwarder/run.py
  #   depends_on:
  #     - redis

  #   environment:
  #     - PYTHONUNBUFFERED=0
  #     - REDIS_ADDRESS=${REDIS_ADDRESS}
  #     - REDIS_PORT=${REDIS_PORT}
  #     - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
  #     - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
  #     - SERVICE_STREAM_KEY=${FORWARDER_STREAM_KEY}
  #     - SERVICE_CMD_KEY=${FORWARDER_CMD_KEY}
  #     - LOGGING_LEVEL=DEBUG
