version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

    mem_limit: 4gb

  media-server:
    image: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"
    volumes:
      - "./media_server/media_files:/var/media_files"
      - "./media_server/nginx.conf:/etc/nginx/nginx.conf"

  query-manager:
    image: registry.insight-centre.org/sit/mps/query-manager:latest
    command: python /service/query_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${QUERY_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${QUERY_MANAGER_CMD_KEY}
      - NAMESPACE_MAPPER_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - MATCHER_CMD_KEY=${MATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  preprocessor:
    # runtime: nvidia
    image: registry.insight-centre.org/sit/mps/preprocessing-service:latest
    command: python /service/preprocessing/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${PREPROCESSOR_STREAM_KEY}
      - SERVICE_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - FFMPEG_BIN=/service/ffmpeg_bin/ffmpeg-linux64-v3.3.1
      - REDIS_EXPIRATION_TIME=10
      - LOGGING_LEVEL=DEBUG
    cpus: 2

  namespace-mapper:
    image: registry.insight-centre.org/sit/mps/namespace-mapper:latest
    command: python /service/namespace_mapper/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${NAMESPACE_MAPPER_STREAM_KEY}
      - SERVICE_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - PREPROCESSOR_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  event-dispatcher:
    image: registry.insight-centre.org/sit/mps/event-dispatcher:latest
    command: python /service/event_dispatcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  window-manager:
    image: registry.insight-centre.org/sit/mps/window-manager:latest
    command: python /service/window_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${WINDOW_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${WINDOW_MANAGER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  state-manager:
    image: registry.insight-centre.org/sit/mps/state-manager:latest
    command: python /service/state_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${STATE_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${STATE_MANAGER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  matcher:
    image: registry.insight-centre.org/sit/mps/matcher:latest
    command: python /service/matcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${MATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${MATCHER_CMD_KEY}
      - FORWARDER_STREAM_KEY=${FORWARDER_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  forwarder:
    image: registry.insight-centre.org/sit/mps/forwarder:latest
    command: python /service/forwarder/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${FORWARDER_STREAM_KEY}
      - SERVICE_CMD_KEY=${FORWARDER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  graph-builder:
    image: registry.insight-centre.org/sit/mps/graph-builder:latest
    command: python /service/graph_builder/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${GRAPH_BUILDER_STREAM_KEY}
      - SERVICE_CMD_KEY=${GRAPH_BUILDER_CMD_KEY}
      - WINDOW_MANAGER_STREAM_KEY=${MATCHER_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  person-detection:
    runtime: nvidia
    image: registry.insight-centre.org/sit/mps/content-extraction-service:latest
    command: python /content-extractor/content_extraction_service/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${PERSON_CONTENT_EXTRACTION_STREAM_KEY}
      - SERVICE_CMD_KEY=${PERSON_CONTENT_EXTRACTION_CMD_KEY}
      - DNN_CONFIG_RETURN_TRUE=True
      - DNN_CONFIG_OBJECT_DETECTION_CLASS=person
      - LOGGING_LEVEL=DEBUG
    cpus: 2

  # car-detection:
  #   image: registry.insight-centre.org/sit/mps/content-extraction-service:latest
  #   command: python /service/content_extraction_service/run.py
  #   depends_on:
  #     - redis

  #   environment:
  #     - PYTHONUNBUFFERED=0
  #     - REDIS_ADDRESS=redis
  #     - REDIS_PORT=${REDIS_PORT}
  #     - SERVICE_STREAM_KEY=${CAR_CONTENT_EXTRACTION_STREAM_KEY}
  #     - SERVICE_CMD_KEY=${CAR_CONTENT_EXTRACTION_CMD_KEY}
  #     - DNN_CONFIG_RETURN_TRUE=True
  #     - DNN_CONFIG_OBJECT_DETECTION_CLASS=car
  #     - LOGGING_LEVEL=DEBUG
  #   cpus: 0.25

  # dog-detection:
  #   image: registry.insight-centre.org/sit/mps/content-extraction-service:latest
  #   command: python /service/content_extraction_service/run.py
  #   depends_on:
  #     - redis

  #   environment:
  #     - PYTHONUNBUFFERED=0
  #     - REDIS_ADDRESS=redis
  #     - REDIS_PORT=${REDIS_PORT}
  #     - SERVICE_STREAM_KEY=${DOG_CONTENT_EXTRACTION_STREAM_KEY}
  #     - SERVICE_CMD_KEY=${DOG_CONTENT_EXTRACTION_CMD_KEY}
  #     - DNN_CONFIG_RETURN_TRUE=True
  #     - DNN_CONFIG_OBJECT_DETECTION_CLASS=dog
  #     - LOGGING_LEVEL=DEBUG
  #   cpus: 0.25