version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

  # media-server:
  #   image: tiangolo/nginx-rtmp
  #   ports:
  #     - "1935:1935"
  #   volumes:
  #     - "./media_server/media_files:/var/media_files"
  #     - "./media_server/nginx.conf:/etc/nginx/nginx.conf"

  preprocessor:
    # runtime: nvidia
    image: registry.insight-centre.org/sit/event-service:latest
    command: python /event-service/event_service/run.py --um
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=redis
      - REDIS_PORT=${REDIS_PORT}
      - EVENT_DISPATCHER_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 1
