version: '2.3'
services:
  media-server:
    image: registry.insight-centre.org/sit/mps/media-server:latest
    ports:
      - "1934:1935"
      - "8080:8080"
    # volumes:
    #   - ./media-server-conf/nginx.conf:/etc/nginx/nginx.conf

  out-media-server:
    image: airensoft/ovenmediaengine:0.15.5

    environment:
      - OME_HOST_IP=*
    ports:
      - "1935:1935"
      - "9999:9999/udp"
      - "9000:9000"
      - "3333:3333"
      - "3334:3334"
      - "3478:3478"
      - 10000-10009:10000-10009/udp

  # media-player:
  #   image: airensoft/ovenplayerdemo:latest
  #   ports:
  #     - "8090:80"
