version: '2.3'
services:
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"

    mem_limit: 4gb

  jaeger:
    # image: jaegertracing/all-in-one:1.7
    image: jaegertracing/all-in-one:1.14
    command: --log-level=debug
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686

  query-manager:
    image: registry.insight-centre.org/sit/mps/query-manager:${IMAGE_TAG}
    command: python /service/query_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${QUERY_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${QUERY_MANAGER_CMD_KEY}
      - NAMESPACE_MAPPER_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - MATCHER_CMD_KEY=${MATCHER_CMD_KEY}
      - QUERY_PLANNER_CMD_KEY=${QUERY_PLANNER_CMD_KEY}
      - FORWARDER_CMD_KEY=${FORWARDER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  query-planner:
    image: registry.insight-centre.org/sit/mps/query-planner:${IMAGE_TAG}
    command: python /service/query_planner/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${QUERY_PLANNER_STREAM_KEY}
      - SERVICE_CMD_KEY=${QUERY_PLANNER_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  preprocessor:
    # runtime: nvidia
    image: registry.insight-centre.org/sit/mps/preprocessing-service:${IMAGE_TAG}
    command: python /service/preprocessing/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${PREPROCESSOR_STREAM_KEY}
      - SERVICE_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - FFMPEG_BIN=/service/ffmpeg_bin/ffmpeg-linux64-v3.3.1
      - REDIS_EXPIRATION_TIME=100
      - LOGGING_LEVEL=DEBUG
    cpus: 2

  namespace-mapper:
    image: registry.insight-centre.org/sit/mps/namespace-mapper:${IMAGE_TAG}
    command: python /service/namespace_mapper/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${NAMESPACE_MAPPER_STREAM_KEY}
      - SERVICE_CMD_KEY=${NAMESPACE_MAPPER_CMD_KEY}
      - PREPROCESSOR_CMD_KEY=${PREPROCESSOR_CMD_KEY}
      - EVENT_DISPATCHER_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  event-dispatcher:
    image: registry.insight-centre.org/sit/mps/event-dispatcher:${IMAGE_TAG}
    command: python /service/event_dispatcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${EVENT_DISPATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${EVENT_DISPATCHER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  window-manager:
    image: registry.insight-centre.org/sit/mps/window-manager:${IMAGE_TAG}
    command: python /service/window_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${WINDOW_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${WINDOW_MANAGER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  state-manager:
    image: registry.insight-centre.org/sit/mps/state-manager:${IMAGE_TAG}
    command: python /service/state_manager/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${STATE_MANAGER_STREAM_KEY}
      - SERVICE_CMD_KEY=${STATE_MANAGER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  matcher:
    image: registry.insight-centre.org/sit/mps/matcher:${IMAGE_TAG}
    command: python /service/matcher/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${MATCHER_STREAM_KEY}
      - SERVICE_CMD_KEY=${MATCHER_CMD_KEY}
      - FORWARDER_STREAM_KEY=${FORWARDER_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  forwarder:
    image: registry.insight-centre.org/sit/mps/forwarder:${IMAGE_TAG}
    command: python /service/forwarder/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${FORWARDER_STREAM_KEY}
      - SERVICE_CMD_KEY=${FORWARDER_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  graph-builder:
    image: registry.insight-centre.org/sit/mps/graph-builder:${IMAGE_TAG}
    command: python /service/graph_builder/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${GRAPH_BUILDER_STREAM_KEY}
      - SERVICE_CMD_KEY=${GRAPH_BUILDER_CMD_KEY}
      - WINDOW_MANAGER_STREAM_KEY=${MATCHER_STREAM_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.25

  object-detection:
    image: registry.insight-centre.org/sit/mps/content-extraction-service:${IMAGE_TAG}
    entrypoint: /content-extractor/entrypoint.sh
    command: python /content-extractor/content_extraction_service/run.py
    depends_on:
     - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - SERVICE_STREAM_KEY=${OBJECT_DETECTION_STREAM_KEY}
      - SERVICE_CMD_KEY=${OBJECT_DETECTION_CMD_KEY}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - DNN_WEIGHTS_PATH=/content-extractor/content_extraction_service/dnn_model/tiny_yolo_voc_v2/yolov2-tiny-voc.weights
      - DNN_CKPT_FOLDER_PATH=/content-extractor/content_extraction_service/dnn_model/tiny_yolo_voc_v2/ckpt/
      - DNN_INPUT_HEIGHT=416
      - DNN_INPUT_WIDTH=416
      - DNN_SCORE_THRESHOLD=0.3
      - DNN_IOU_THRESHOLD=0.3
      - DNN_TF_GPU_FRACTION=0.25
      - LOGGING_LEVEL=DEBUG
    cpus: 1
    mem_limit: 1500mb

  color-detection:
    image: registry.insight-centre.org/sit/mps/color-detection-service:${IMAGE_TAG}
    command: python /service/color_detection_service/run.py
    depends_on:
      - redis

    environment:
      - PYTHONUNBUFFERED=0
      - REDIS_ADDRESS=${REDIS_ADDRESS}
      - REDIS_PORT=${REDIS_PORT}
      - TRACER_REPORTING_HOST=${TRACER_REPORTING_HOST}
      - TRACER_REPORTING_PORT=${TRACER_REPORTING_PORT}
      - SERVICE_STREAM_KEY=${COLOR_DETECTION_STREAM_KEY}
      - SERVICE_CMD_KEY=${COLOR_DETECTION_CMD_KEY}
      - LOGGING_LEVEL=DEBUG
    cpus: 0.5
    mem_limit: 100mb
